
plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.9'
    id 'com.teamdev.jxbrowser' version '1.0.1'
//    id 'org.beryx.jlink' version '2.24.0'
}

javafx {
    version = "22"
    modules = [ 'javafx.controls', 'javafx.swing','javafx.web']
}

group 'org.example'
version '1.0.18'

repositories {
    mavenCentral()

    maven {
        url "https://packages.atlassian.com/maven-public/"
    }

    maven{
        url "https://www.dcm4che.org/maven2/"
    }

    maven { url 'https://jitpack.io' }

}
jxbrowser {
    version '7.37.1'
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.7.0'
    implementation group: 'org.jcodec', name: 'jcodec', version: '0.2.5'
    implementation group: 'org.jcodec', name: 'jcodec-javase', version: '0.2.5'

    implementation 'org.scilab.forge:jlatexmath:1.0.7'

    implementation group: 'org.apache.xmlgraphics', name: 'batik-bridge', version: '1.14'
    implementation group: 'org.apache.xmlgraphics', name: 'batik-dom', version: '1.14'
    implementation group: 'xuggle', name: 'xuggle-xuggler', version: '5.4'
    implementation group: 'org.apache.logging.log4j', name: 'log4j-slf4j-impl', version: '2.14.1'
    implementation 'org.jfree:org.jfree.fxgraphics2d:2.1.2'
    implementation 'com.github.sealedtx:java-youtube-downloader:3.0.1'
    implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.14.0'
    implementation group: 'com.fifesoft', name: 'rsyntaxtextarea', version: '3.1.1'
    implementation group: 'com.fifesoft', name: 'autocomplete', version: '3.3.1'
    implementation group: 'com.fifesoft', name: 'languagesupport', version: '3.3.0'

    implementation 'net.java.dev.jna:jna:5.9.0'
    implementation 'net.java.dev.jna:jna-platform:5.9.0'
//    implementation jxbrowser.crossPlatform
//    implementation jxbrowser.swing

    implementation 'org.fxyz3d:fxyz3d-importers:0.6.0'

    implementation 'me.friwi:jcefmaven:122.1.10'

}


test {
    useJUnitPlatform()
}


jar {

    manifest {
        attributes 'Main-Class': 'graphical.basics.animations.ifood2.ifoodAnim2'
    }

    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}


